services:
  db:
    image: mongo:4.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    ports:
      - 27018:27017
    volumes:
      - type: bind
        source: .db-data
        target: /data/db
volumes:
  .db-data: