services:
  db:
    image: mongo:4.4
    container_name: ${DB_CONTAINER_NAME}
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - .db-data:/data/db
  server:
    build: ./
    command: ./init.sh
    ports:
      - 8080:8080
    depends_on:
      - db
volumes:
  .db-data: